viewpoint_generation_node:
  ros__parameters:
    visualize: True
    cuda_enabled: False

    model:
      triangle_mesh_file: "package://viewpoint_generation/assets/cube_beveled.stl"
      triangle_mesh_units: 'in'
      point_cloud_file: ""
      point_cloud_units: 'in'

    pcd_sampling:
      ppsqmm: 4.
      number_of_points: 100000
      sample_point_cloud: False
    
    curvature:
      number_of_neighbors: 30
      estimate_curvature: False

    camera:
      fov_width: 0.02
      fov_height: 0.03
      dof: 0.02
      focal_distance: 0.35

    regions:
      region_growth: False
