viewpoint_generation_node:
  ros__parameters:
    model:
      mesh:
        file: "package://viewpoint_generation/assets/blade.stl"
        units: 'mm'
      point_cloud:
        file: "package://viewpoint_generation/assets/blade.ply"
        units: 'mm'
        sampling:
          ppsqmm: 4.
          number_of_points: 100000

    camera:
      fov:
        width: 0.02
        height: 0.03
      dof: 0.02
      focal_distance: 0.35

    regions:
      file: ""
      region_growth:
        curvature:
          knn_neighbors: 10
          file: "package://viewpoint_generation/assets/blade_pcd/blade_pcd_100000points_10nn_curvature.npy"
        seed_threshold: 0.1
        min_cluster_size: 100
        max_cluster_size: 100000
        curvature_threshold: 0.1
        normal_angle_threshold: 45.0
      fov_clustering:
        lambda_weight: 1.0
        beta_weight: 1.0
        max_point_out_percentage: 0.001
        k-means:
          point_weight: 1.0
          normal_weight: 1.0
          number_of_runs: 10
          maximum_iterations: 100


    viewpoints:
      nothing: ''

    traversal:
      nothing: ''

    settings:
      cuda_enabled: False



