viewpoint_generation_node:
  ros__parameters:
    model:
      mesh:
        file: "package://viewpoint_generation/assets/blade.stl"
        units: 'mm'
      point_cloud:
        file: "package://viewpoint_generation/assets/blade.ply"
        units: 'mm'
        sampling:
          ppsqmm: 4.
          number_of_points: 100000
        curvature:
          file: "package://viewpoint_generation/assets/blade_pcd/blade_pcd_100000points_10nn_curvature.npy"
          number_of_neighbors: 10

    camera:
      fov:
        width: 0.02
        height: 0.03
      dof: 0.02
      focal_distance: 0.35

    regions:
      file: ""
      region_growth:
        curvature_threshold: 0.0
        angle_threshold: 15.0

    settings:
      cuda_enabled: False



