gui:
  ros__parameters:
    show_model_bounding_box: False
    show_grid: False
    show_skybox: True
    show_mesh: True
    show_point_cloud: False
    show_curvatures: False
    show_regions: False
    show_noise_points: False
    show_fov_clusters: False
    show_viewpoints: False
    show_region_view_manifolds: False
    show_reticle: True
    show_path: False

task_planning:
  ros__parameters:
    viewpoints_file: "$INSPECTION_WS/src/ViewpointGenerationData/turbine_blade_point_cloud/turbine_blade_mm_point_cloud_100000points_0.1_100_100000_0.1_0.1_0.5235987755982988_2025-08-19_14-14-00_viewpoints_optimized2025-08-19_16-17-34.json"

viewpoint_generation:
  ros__parameters:
    model:
      mesh:
        file: "$INSPECTION_WS/src/ViewpointGenerationData/turbine_blade.stl"
        units: 'mm'
      point_cloud:
        file: "$INSPECTION_WS/src/ViewpointGenerationData/turbine_blade_point_cloud/turbine_blade_mm_point_cloud_100000points.ply"
        units: 'm'
        sampling:
          ppsqmm: 4.
          number_of_points: 100000
      camera:
        fov:
          width: 0.1
          height: 0.1
        dof: 0.02
        focal_distance: 0.3

    regions:
      file: "$INSPECTION_WS/src/ViewpointGenerationData/turbine_blade_point_cloud/turbine_blade_mm_point_cloud_100000points_0.1_100_100000_0.1_0.1_0.5235987755982988_2025-08-19_14-14-00_viewpoints_optimized2025-08-19_16-17-34.json"
      region_growth:
        curvature:
          file: "$INSPECTION_WS/src/ViewpointGenerationData/turbine_blade_point_cloud/turbine_blade_mm_point_cloud_100000points_10nn_curvatures.npy"
          knn_neighbors: 10
        seed_threshold: 0.1
        min_cluster_size: 100
        max_cluster_size: 100000
        curvature_threshold: 0.1
        normal_angle_threshold: 60.0
      fov_clustering:
        lambda_weight: 1.0
        beta_weight: 1.0
        max_point_out_percentage: 0.001
        k-means:
          point_weight: 1.0
          normal_weight: 1.0
          number_of_runs: 10
          maximum_iterations: 100
    selected_region: 0


    viewpoints:
      traversal: ''
      projection:
        nothing: ''


    settings:
      cuda_enabled: False



